version: "3"
services:
  zaproxy_ui:
    env_file: .env
    image: quay.io/redhatproductsecurity/rapidast-base-zap
    container_name: zaproxy
    user: zap
    ports:
      - "127.0.0.1:8091:8090"
      - "127.0.0.1:8081:8080"
    volumes:
      - ./scripts:/zap/scripts:Z
      - ./config:/zap/config:Z
      - ./results:/zap/results:Z
      - ./policies:/zap/policies:Z
      - ./webswing:/zap/webswing_custom:Z
    entrypoint: /zap/scripts/entrypoint_ui.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
