version: "3"
services:
  zaproxy_ui:
    env_file: .env
    image: docker.io/owasp/zap2docker-stable
    container_name: zaproxy
    user: zap
    ports:
      - "127.0.0.1:8091:8090"
      - "127.0.0.1:8081:8080"
    volumes:
      - ./scripts:/zap/scripts:Z
      - ./config:/zap/config:Z
      - ./results:/zap/results:Z,U
      - ./policies:/zap/policies:Z
      - ./webswing:/zap/webswing_custom:Z
    entrypoint: /zap/scripts/entrypoint_ui.sh
