version: "3"
services:
  zaproxy:
    env_file: .env
    image: quay.io/redhatproductsecurity/rapidast-base-zap
    container_name: zaproxy
    user: zap
    ports:
      - "8091:8090"
    volumes:
      - ./scripts:/zap/scripts:Z
      - ./config:/zap/config:Z
      - ./results:/zap/results:Z
      - ./policies:/zap/policies:Z
      - ./requirements.txt:/zap/requirements.txt:Z
    entrypoint: /zap/scripts/entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
