apiVersion: v1
kind: Service
metadata:
  labels:
    app: fake-gcs-server
  name: fake-gcs-server
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - protocol: TCP
    port: 4443
    targetPort: 4443
    name: http
  selector:
    app: fake-gcs-server
  sessionAffinity: None
  type: ClusterIP
