apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: rapidast-vapi
spec:
  initContainers:
    # Run rapidast as initContainer, second container prints the results
  - image: ${IMAGE} # quay.io/redhatproductsecurity/rapidast:latest
    imagePullPolicy: Always
    name: rapidast
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
    volumeMounts:
    - name: config-volume
      mountPath: /opt/rapidast/config
    - name: results
      mountPath: /opt/rapidast/results
  containers:
    # Expects initContainer to already have created results
  - command: ["bash", "-c", "cat /opt/rapidast/results/*/*/zap/zap-report.json"]
    image: registry.redhat.io/ubi9/ubi-micro
    name: results
    volumeMounts:
    - name: results
      mountPath: /opt/rapidast/results
  volumes:
  - name: config-volume
    configMap:
      name: rapidast-vapi
  - name: results
    emptyDir: {}
  restartPolicy: Never
