apiVersion: v1
data:
  config.yaml: |+
    config:
      configVersion: 5

    # `application` contains data related to the application, not to the scans.
    application:
      shortName: "v5-none-release-test"
      url: "http://vapi:5000"

    scanners:
      zap:
        apiScan:
          apis:
            apiUrl: "http://vapi:5000/docs/openapi.json"

        passiveScan:
          # optional list of passive rules to disable
          disabledRules: "2,10015,10027,10096,10024,10098,10023,10105"

        activeScan:
          policy: API-scan-minimal

        spiderAjax:
          maxDuration: 1
          url: "http://vapi:3000"
          maxCrawlDepth: 1

        miscOptions:
          updateAddons: False

        urls:
          excludes:
          - "http://vapi:5000/api/pets/id/.*"
          - "http://vapi:3000/_next/static/css/.*.css"

kind: ConfigMap
metadata:
  name: rapidast-vapi
