apiVersion: v1
data:
  config.yaml: |+
    config:
      configVersion: 5

    # `application` contains data related to the application, not to the scans.
    application:
      shortName: "oobttest"

    general:
      container:
        # currently supported: `podman` and `none`
        type: "none"

    scanners:
      generic_1:
        # results:
        #   An absolute path to file or directory where results are stored on the host.
        #   if it is "*stdout" or unspecified, the command's standard output will be selected
        results: "/tmp/oobtkube.sarif.json"   # if None or "*stdout", the command's standard output is selected
        # toolDir: scanners/generic/tools
        inline: |
          PYTHON_VERSION="${PYTHON_VERSION:-python3}"
          $PYTHON_VERSION oobtkube.py --log-level debug -d 60 -p 6000 -i rapidast-oobtkube -f /opt/rapidast/config/cr_example.yaml | tee /tmp/oobtkube.sarif.json
  # ConfigMap is used as target because it is a default resource
  cr_example.yaml: |+
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: vulnerable
    data:
      foo: bar
      target: foobar

kind: ConfigMap
metadata:
  name: rapidast-oobtkube
