apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: rapidast-oobtkube
  labels:
    app: rapidast-oobtkube
spec:
  containers:
  - image: ${IMAGE} # quay.io/redhatproductsecurity/rapidast:latest
    imagePullPolicy: Always
    name: rapidast-oobtkube
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi
    volumeMounts:
    - name: config-volume
      mountPath: /opt/rapidast/config
  serviceAccountName: ${SERVICEACCOUNT} # oobtkube needs perms to query API server
  volumes:
  - name: config-volume
    configMap:
      name: rapidast-oobtkube
  restartPolicy: Never
