apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: rapidast-trivy
spec:
  containers:
  - image: ${IMAGE} # quay.io/redhatproductsecurity/rapidast:latest
    imagePullPolicy: Always
    name: rapidast-trivy
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 125m
        memory: 256Mi
    volumeMounts:
    - name: config-volume
      mountPath: /opt/rapidast/config
  serviceAccountName: ${SERVICEACCOUNT} # trivy needs perms to query API server
  volumes:
  - name: config-volume
    configMap:
      name: rapidast-trivy
  restartPolicy: Never
