apiVersion: v1
kind: Service
metadata:
  labels:
    app: rapidast-oobtkube
  name: rapidast-oobtkube
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: rapidast-oobtkube
  sessionAffinity: None
  type: ClusterIP
