apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: rapidast-vapi
spec:
  containers:
  - command:
    - bash
    - -c
    - "./rapidast.py && cat results/*/*/zap/zap-report.json" # ugly, but saves needing a PVC to retrieve .json file after execution
    image: ${IMAGE} # quay.io/redhatproductsecurity/rapidast:latest
    imagePullPolicy: Always
    name: rapidast-vapi
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
    volumeMounts:
    - name: config-volume
      mountPath: /opt/rapidast/config
  volumes:
  - name: config-volume
    configMap:
      name: rapidast-vapi
  restartPolicy: Never
