apiVersion: v1
kind: Service
metadata:
  labels:
    app: vapi
  name: vapi
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: backend
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: frontend
  selector:
    app: vapi
  sessionAffinity: None
  type: ClusterIP
