---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: vapi-auth
  labels:
    app: vapi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vapi-auth
  template:
    metadata:
      labels:
        app: vapi-auth
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          cd /app && python3 run.py
        env:
        - name: VAPI_HOST
          value: 0.0.0.0
        - name: VAPI_PORT
          value: "5000"
        - name: VAPI_FRONTEND_PORT
          value: "3000"
        image: quay.io/redhatproductsecurity/vapi:1.6.0
        imagePullPolicy: IfNotPresent
        name: vapi-auth
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
