# permissions for end users to edit rapidastccs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rapidastcc-editor-role
rules:
- apiGroups:
  - research.psse
  resources:
  - rapidastccs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - research.psse
  resources:
  - rapidastccs/status
  verbs:
  - get
