# permissions for end users to view rapidasts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rapidast-viewer-role
rules:
- apiGroups:
  - research.psse
  resources:
  - rapidasts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - research.psse
  resources:
  - rapidasts/status
  verbs:
  - get
