# permissions for end users to edit rapidasts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rapidast-editor-role
rules:
- apiGroups:
  - research.psse
  resources:
  - rapidasts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - research.psse
  resources:
  - rapidasts/status
  verbs:
  - get
