config:
  # WARNING: `configVersion` indicates the schema version of the config file.
  # This value tells RapiDAST what schema should be used to read this configuration.
  # Therefore you should only change it if you update the configuration to a newer schema
  configVersion: 6

  # all the results of all scanners will be stored under that location
  # base_results_dir: "./results"

# `application` contains data related to the application, not to the scans.
application:
  shortName: "garak-test-1.0"
  # url: "<Mandatory. root URL of the application>" # unused for Garak

# `scanners' is a section that configures scanning options
scanners:
  garak:
    model_name: gpt2
    model_type: huggingface
    probe_spec: dan.Dan_11_0         # default: all, or a list of probes like "probe1,probe2"
    #garak_executable_path: /usr/local/bin/garak      # default: /usr/local/bin/garak
