---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rapidast-e2e
spec:
  params:
    - name: repo_url
      default: github.com/RedHatProductSecurity/rapidast
    - name: revision
      default: "development"
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: |-
          '{
            "components": [
              {
                "name":"rapidast",
                "containerImage": "quay.io/redhatproductsecurity/rapidast:latest",
                "source":{
                  "git":{
                    "url":"git@github.com:RedHatProductSecurity/rapidast.git",
                    "revision":"development",
                  }
                }
              }
            ]
          }'
      type: string

  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)

    - name: provision-eaas-space-nessus
      runAfter:
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)

    - name: copy-nessus-secret
      runAfter:
       - provision-eaas-space-nessus
      taskSpec:
        steps:
          - name: copy-nessus-secret
            image: registry.redhat.io/openshift4/ose-cli:latest
            env:
            - name: KUBECONFIG
              value: /tmp/kubeconfig
            - name: EAAS_KUBECONFIG_VALUE
              valueFrom:
                secretKeyRef:
                  name: $(tasks.provision-eaas-space-nessus.results.secretRef)
                  key: kubeconfig
            workingDir: /workspace
            script: |
              #!/bin/bash -ex

              # initial request will default to in-cluster k8s config
              oc whoami
              oc get secret sfowler-nessus-pull-secret -o yaml > /tmp/nessus-pull-secret.yaml
              sed '/namespace:/d' /tmp/nessus-pull-secret.yaml > /tmp/new-secret.yaml

              # second request should use newly provisioned eaas creds + namespace
              echo "$EAAS_KUBECONFIG_VALUE" > "$KUBECONFIG"
              oc whoami
              oc apply -f /tmp/new-secret.yaml

    - name: provision-eaas-space
      runAfter:
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)

    - name: prefetch-get-refs
      onError: continue
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/RedHatProductSecurity/rapidast
        - name: revision
          value: prefetch-pip-deps-e2e-konflux
        - name: pathInRepo
          value: .tekton/tasks/prefetch-get-refs.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)

    # XXX integrations tests can't reference Tasks in the same PR AFAICT
    # so need to repeat them inline, rather than define in a separate file
    - name: run-e2e-tests
      runAfter:
        - provision-eaas-space
        - prefetch-get-refs
      taskSpec:
        stepTemplate:
          volumeMounts:
            - mountPath: /cachi2
              name: cachi2
        volumes:
          - name: credentials
            emptyDir: {}
          - name: cachi2
            emptyDir: {}
        results:
          - name: TEST_OUTPUT
            description: e2e test results
        steps:
          # XXX not supported to use workspaces in integration tests
          - name: clone-repository
            image: quay.io/konflux-ci/git-clone:latest
            script: |
              git config --global --add safe.directory /workspace
              git clone "$(tasks.parse-metadata.results.source-git-url)" /workspace
              pushd /workspace
              git checkout "$(tasks.parse-metadata.results.source-git-revision)"
          - name: use-trusted-artifact
            image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:8391272c4e5011120e9e7fee2c1f339e9405366110bf239dadcbc21e953ce099
            env:
              - name: PREFETCH_CACHI2_ARTIFACT
                value: $(tasks.prefetch-get-refs.results.PREFETCH_CACHI2_ARTIFACT)
            args:
              - use
              - $PREFETCH_CACHI2_ARTIFACT=/cachi2
            when:
              - input: "$(tasks.prefetch-get-refs.results.PREFETCH_CACHI2_ARTIFACT)"
                operator: notin
                values: [""]
          - name: inject-cachi2-files
            image: quay.io/konflux-ci/cachi2:0.20.0@sha256:80402886bbc0f6b4deba65cf5f66dfe9a2c01ae0b57bf3454e3ea58e1a395720
            workingDir: /workspace
            script: |
              cachi2 --log-level="debug" inject-files /cachi2/output
            when:
              - input: "$(tasks.prefetch-get-refs.results.PREFETCH_CACHI2_ARTIFACT)"
                operator: notin
                values: [""]
          - name: test
            image: registry.redhat.io/openshift4/ose-cli:latest
            env:
            - name: KUBECONFIG
              value: /tmp/kubeconfig
            - name: KUBECONFIG_VALUE
              valueFrom:
                secretKeyRef:
                  name: $(tasks.provision-eaas-space.results.secretRef)
                  key: kubeconfig
            - name: RAPIDAST_CLEANUP
              value: "false" # namespace will be cleaned up automatically
            - name: RAPIDAST_IMAGE
              value: $(tasks.parse-metadata.results.component-container-image)
            - name: RAPIDAST_SERVICEACCOUNT
              value: namespace-manager # created by provision-env-with-ephemeral-namespace
            workingDir: /workspace
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/bash -ex

              echo "$KUBECONFIG_VALUE" > "$KUBECONFIG"
              oc whoami

              yum install -y python3.12 git
              python3.12 -m ensurepip

              if [ -f "/cachi2/cachi2.env" ]; then
                echo "Sourcing Cachi2 environment"
                source /cachi2/cachi2.env
              fi

              pip3 install -r requirements-dev.txt
              pytest -s e2e-tests/test_integration.py --json-report --json-report-summary --json-report-file $(results.TEST_OUTPUT.path)
              cat $(results.TEST_OUTPUT.path)

    - name: run-e2e-tests-nessus
      runAfter:
        - copy-nessus-secret
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: {}
        results:
          - name: TEST_OUTPUT
            description: e2e test results
        steps:

          # XXX not supported to use workspaces in integration tests:
          # * https://issues.redhat.com/browse/STONEINTG-895
          - name: clone-repository
            image: quay.io/konflux-ci/git-clone:latest
            script: |
              git config --global --add safe.directory /workspace
              git clone "$(tasks.parse-metadata.results.source-git-url)" /workspace
              pushd /workspace
              git checkout "$(tasks.parse-metadata.results.source-git-revision)"

          - name: test
            image: registry.redhat.io/openshift4/ose-cli:latest
            env:
            - name: KUBECONFIG
              value: /tmp/kubeconfig
            - name: KUBECONFIG_VALUE
              valueFrom:
                secretKeyRef:
                  name: $(tasks.provision-eaas-space-nessus.results.secretRef)
                  key: kubeconfig
            - name: RAPIDAST_CLEANUP
              value: "false" # namespace will be cleaned up automatically
            - name: RAPIDAST_IMAGE
              value: $(tasks.parse-metadata.results.component-container-image)
            - name: RAPIDAST_SERVICEACCOUNT
              value: namespace-manager # created by provision-env-with-ephemeral-namespace
            workingDir: /workspace
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              #!/bin/bash -ex

              echo "$KUBECONFIG_VALUE" > "$KUBECONFIG"
              oc whoami

              yum install -y python3.12 git
              python3.12 -m ensurepip
              pip3 install -r requirements-dev.txt
              pytest -sv e2e-tests/test_nessus.py --json-report --json-report-summary --json-report-file $(results.TEST_OUTPUT.path)
              cat $(results.TEST_OUTPUT.path)
