apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatProductSecurity/rapidast?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && (target_branch == "development" || target_branch == "main")
  labels:
    appstudio.openshift.io/application: rapidast
    appstudio.openshift.io/component: rapidast
    pipelines.appstudio.openshift.io/type: build
  name: rapidast-on-pull-request
  namespace: secaut-tenant
spec:
  pipelineRef:
    name: rapidast-pipeline
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhatproductsecurity/rapidast:on-pr-{{revision}}
  - name: image-expires-after
    value: 7d
  - name: dockerfile
    value: containerize/Containerfile
  - name: skip-checks
    value: "false"
  - name: prefetch-input
    value:
    - {"type": "generic", "path": "."}
    - {"type": "npm", "path": "."}
    - {"type": "pip", "path": ".", "allow_binary": "true", "requirements_files": ["requirements-dev.txt"]}
  - name: build-args
    value: [PREFETCH=true]
  taskRunSpecs:
    - pipelineTaskName: ecosystem-cert-preflight-checks
      stepSpecs:
        - name: app-check
          computeResources:
            requests:
              memory: 512Mi
            limits:
              memory: 4Gi
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
