apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatProductSecurity/rapidast?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && (target_branch
      == "development" || target_branch == "main")
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rapidast
    appstudio.openshift.io/component: rapidast
    pipelines.appstudio.openshift.io/type: build
  name: rapidast-on-push
  namespace: secaut-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhatproductsecurity/rapidast:{{revision}}
  - name: dockerfile
    value: containerize/Containerfile
  - name: prefetch-input
    value: '[{"path":".","type":"generic"},{"path":".","type":"npm"},{"allow_binary":"true","path":".","requirements_files":["requirements-dev.txt"],"type":"pip"}]'
  - name: build-args
    value:
    - PREFETCH=true
  pipelineRef:
    name: rapidast-pipeline
  taskRunSpecs:
  - pipelineTaskName: ecosystem-cert-preflight-checks
    stepSpecs:
    - computeResources:
        limits:
          memory: 4Gi
        requests:
          memory: 512Mi
      name: app-check
  taskRunTemplate:
    serviceAccountName: build-pipeline-rapidast
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
