apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-e2e-tests
spec:
  description: |
    runs the rapidast e2e tests
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: rapidast_image
      type: string
    - name: eaas_secret_name
      type: string
    - name: test_filter
      type: string
      default: ""
  volumes:
    - name: credentials
      emptyDir: {}
  results:
    - name: TEST_RESULTS
      description: e2e test results
  steps:
    # XXX not supported to use workspaces in integration tests:
    # * https://issues.redhat.com/browse/STONEINTG-895
    - name: clone-repository
      image: quay.io/konflux-ci/git-clone:latest
      script: |
        git config --global --add safe.directory /workspace
        git clone "$(params.git-url)" /workspace
        pushd /workspace
        git checkout "$(params.git-revision)"

    - name: test
      image: registry.redhat.io/openshift4/ose-cli:latest
      env:
      - name: KUBECONFIG
        value: /tmp/kubeconfig
      - name: KUBECONFIG_VALUE
        valueFrom:
          secretKeyRef:
            name: $(params.eaas_secret_name)
            key: kubeconfig
      - name: RAPIDAST_CLEANUP
        value: "false" # namespace will be cleaned up automatically
      - name: RAPIDAST_IMAGE
        value: $(params.rapidast_image)
      - name: RAPIDAST_SERVICEACCOUNT
        value: namespace-manager # created by provision-env-with-ephemeral-namespace
      workingDir: /workspace
      volumeMounts:
        - name: credentials
          mountPath: /credentials
      script: |
        #!/bin/bash -ex

        echo "$KUBECONFIG_VALUE" > "$KUBECONFIG"
        oc whoami

        yum install -y python3.12 git
        python3.12 -m ensurepip
        pip3 install -r requirements.txt -r requirements-dev.txt
        pytest -s e2e-tests -k $(params.test_filter) --json-report --json-report-summary --json-report-file $(results.TEST_RESULTS.path)
        cat $(results.TEST_RESULTS.path)
