name: Build container image

env:
  IMAGE_NAME: "rapidast"
  IMAGE_TAGS: "${{ github.sha }}"

on:
  pull_request:
    branches: ["development", "main"]

jobs:

  build-image:

    runs-on: ubuntu-latest

    # https://github.com/redhat-actions/buildah-build#readme
    steps:
    - uses: actions/checkout@v4
    - name: Build container image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
            ./containerize/Containerfile
