name: Run tests

on:
  push:
    branches: ["development", "main"]
  pull_request:
    branches: ["development", "main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # actions/checkout@v6
    - name: Set up Python 3.12
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Install dependencies
      run: |
        python3.12 -m ensurepip --upgrade
        python3.12 -m pip install -r requirements-dev.txt
    - name: Lint with pre-commit hook
      run: |
        pre-commit run --all-files --show-diff-on-failure

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # actions/checkout@v6
    - name: Set up Python 3.12
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Install dependencies
      run: |
        python3.12 -m ensurepip --upgrade
        python3.12 -m pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pytest tests
