name: Run tests

on:
  push:
    branches: ["development"] # XXX for now 'main' is removed to reduce time. It may be added again later.
  pull_request:
    branches: ["development", "main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Install dependencies
      run: |
        python3 -m ensurepip --upgrade
        pip install -r requirements-dev.txt
    - name: Lint with pre-commit hook
      run: |
        pre-commit run --all-files --show-diff-on-failure

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Install dependencies
      run: |
        python3 -m ensurepip --upgrade
        pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pytest tests
