name: "Validate renovate.json config"

on:
  push:
    branches: ["development", "main"]
    paths:
      - "renovate.json"
  pull_request:
    branches: ["development", "main"]
    paths:
      - "renovate.json"

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # actions/checkout@v6
      - uses: konflux-ci/renovate-config-validator-action@078d8d5e483879bcb260de0f717be30b59df010c  # konflux-ci/renovate-config-validator-action@main
